### ISSUE TITLE
TypeError on tracer method

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/apollo-server#25] opened 2016-06-13 00:48 UTC
Tracer.submit is not a function

https://github.com/apollostack/apollo-server/blob/master/src/apolloServer.js#L254

**Comment by helfer** [comment] 2016-06-13 01:25
I think the problem is here:

https://github.com/apollostack/apollo-server/blob/853ebfbda3360104c505073d3b17c0905cefc3eb/src/apolloServer.js#L138

I'm a bit confused as to why that hasn't caused any test to fail, tbh.

Also, might be worth noting here that the tracer code itself is no longer in apollo server. You have to import it from the apollo-tracer pacakge.

**Comment by helfer** [comment] 2016-06-13 18:16
Fixed by #26

**Closed by helfer** 2016-06-13 18:16 UTC
