### ISSUE TITLE
tracerLogger.submit is not a function

### ISSUE THREAD

**Issue by whitecolor** [apollostack/apollo-server#30] opened 2016-06-15 14:25 UTC
Trying apollo server.
Just got an error:
```
Unhandled rejection TypeError: tracerLogger.submit is not a function
```

**Comment by helfer** [comment] 2016-06-15 16:49
This should have been fixed by an earlier PR. We didn't publish a new version for that though. Will do so now. After an update this error should be gone.

**Comment by whitecolor** [comment] 2016-06-15 19:20
I have also got the error after make this correcton
```
 rejection TypeError: Cannot read property 'submit' of undefined
```

**Comment by helfer** [comment] 2016-06-15 19:26
You're saying you get this error with 0.1.5? @jbaxleyiii can you confirm?

**Comment by whitecolor** [comment] 2016-06-15 19:33
Yes update version 0.1.5
I get the error probably you can add illegal item to schema:
```
  schema {
    query: Query
    mutation: Mutation
    notation: Notation
  }
```
At least I get this error no this and trying access `/graphql` endpoint

**Comment by helfer** [comment] 2016-06-15 19:41
I'm assuming you get this error in the console on the server, but it still works and you get a response on the client, right?

**Comment by whitecolor** [comment] 2016-06-15 19:44
no, client sends error, breaks server

**Comment by helfer** [comment] 2016-06-15 21:14
@whitecolor: Do you have a full stack trace on the server and/or the client?

**Comment by whitecolor** [comment] 2016-06-16 08:24
```
Unhandled rejection TypeError: Cannot read property 'submit' of undefined
    at ...\node_modules\apollo-server\dist\apolloServer.js:289:19
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at ...\node_modules\apollo-server\dist\apolloServer.js:287:8
    at Layer.handle [as handle_request] (...\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\node_modules\express\lib\router\index.js:312:13)
    at ...\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (...\node_modules\express\lib\router\index.js:330:12)
    at next (...\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (...\node_modules\express\lib\router\index.js:176:3)
    at router (...\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (...\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\node_modules\express\lib\router\index.js:312:13)
    at ...\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (...\node_modules\express\lib\router\index.js:330:12)
    at next (...\node_modules\express\lib\router\index.js:271:10)
    at ...\server\index.js:63:7
    at Layer.handle [as handle_request] (...\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\node_modules\express\lib\router\index.js:312:13)
    at ...\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (...\node_modules\express\lib\router\index.js:330:12)
    at next (...\node_modules\express\lib\router\index.js:271:10)
    at expressInit (...\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (...\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...\node_modules\express\lib\router\index.js:312:13)
    at ...\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (...\node_modules\express\lib\router\index.js:330:12)
    at next (...\node_modules\express\lib\router\index.js:271:1
```

**Comment by helfer** [comment] 2016-06-16 18:31
That is indeed the line I thought it was. I'm not sure why this works in our tests, but not in your code. Could you provide a minimal reproduction so I can run it and debug it myself?

**Comment by whitecolor** [comment] 2016-06-16 18:43
Have you tried do such thing:
```
 schema {
    query: Query
    mutation: Mutation
    notation: Notation
  }
```
and register apolloServer with such schema, then access graphiQL?

**Comment by helfer** [comment] 2016-06-16 18:51
I'm 99% sure that that's not the cause of the error you're observing, so I don't think it's worth trying. The easiest way for me to find out what's going on is if you could make a repo on GitHub and instructions for how to reproduce the error with the code in that repo.

**Comment by whitecolor** [comment] 2016-06-16 18:57
The easiest  way for me is not make such mistake and don't get this error ;)
Ok, if I will be able I will try to provide reproduction.

**Comment by helfer** [comment] 2016-06-29 17:59
@whitecolor any update on the reproduction? I would love to see one, so we can debug this.

**Comment by whitecolor** [comment] 2016-06-29 20:02
No, I think may be closed. If I will encounter and reproduce can be reopened then.

**Comment by helfer** [comment] 2016-06-30 00:12
Okay, thanks!

**Closed by helfer** 2016-06-30 00:12 UTC

**Comment by linonetwo** [comment] 2016-09-26 02:24
Any progress on this? I get into the same problem in OSX using graphql-tools 0.4.2 but with nothing wrong in Windows.

**Comment by linonetwo** [comment] 2016-09-26 02:25
@whitecolor are you using OSX?

**Comment by helfer** [comment] 2016-09-26 02:40
@linonetwo which version of apollo-server are you using? Any code referring to tracer was removed in 0.2, afaik.

**Comment by linonetwo** [comment] 2016-09-26 02:55
@helfer Sorry for that, I was on client side graphQL server for too long, not knowing server side server has upgraded to apollo-server. After upgrading to apollo-server, everything is fine 👍
